### ISSUE TITLE
Exception - Call to undefined method mysqli_native_moodle_database::delete_record()

### ISSUE THREAD

**Issue by NMCPaul** [bmbrands/moodle-local_analytics#29]
When upgrading the plugin on Moodle v3.6.5+ from commit 902f353 to commit c6c52e9, I'm getting the error  in the title.

**Comment by Venator-Fox** [comment]
My colleague @jyounggo found that the method name could be `delete_records` instead of `delete_record`. I also went ahead and adjusted the syntax to how `delete_records` is used as per some other examples such as in `https://tracker.moodle.org/browse/MDL-62875`

This seemed to allow us to upgrade without errors. Would need @bmbrands to verify the PR though as I am not sure if this is actually doing what he originally intended.

**Comment by bmbrands** [comment]
Hi @Venator-Fox 
Thanks for working on this. I think the solution by Tom is best.
